repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.2.0 # https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint
        files: playbook\.(yaml|yml)$
